---

language: elixir
elixir:
  - 1.6.6
  - 1.8.2
  - 1.9.4
  - 1.10.4
otp_release:
  - 20.0
  - 20.3.8.22
  - 21.3.8
  - 22.1.3
  - 23.0.4
matrix:
  include:
    - elixir: 1.5.3
      otp_release: 20.0
      env: SKIP_DIALYZER=true
    - elixir: 1.5.3
      otp_release: 20.3.8.22
      env: SKIP_DIALYZER=true
    - elixir: 1.7.4
      otp_release: 20.0
      env: SKIP_DIALYZER=false
    - elixir: 1.7.4
      otp_release: 20.3.8.22
      env: SKIP_DIALYZER=false
    - elixir: 1.7.4
      otp_release: 21.3.8
      env: SKIP_DIALYZER=true
    - elixir: 1.7.4
      otp_release: 22.1.3
      env: SKIP_DIALYZER=true
    - elixir: 1.7.4
      otp_release: 23.0.4
      env: SKIP_DIALYZER=true
  exclude:
    - elixir: 1.5.3
      otp_release: 21.3.8
    - elixir: 1.5.3
      otp_release: 22.1.3
    - elixir: 1.5.3
      otp_release: 23.0.4
    - elixir: 1.6.6
      otp_release: 22.1.3
    - elixir: 1.6.6
      otp_release: 23.0.4
    - elixir: 1.8.2
      otp_release: 23.0.4
    - elixir: 1.9.4
      otp_release: 23.0.4
    - elixir: 1.10.4
      otp_release: 20.0
    - elixir: 1.10.4
      otp_release: 20.3.8.22

script:
  - mix format --check-formatted
  - mix test
  - if [ "$SKIP_DIALYZER" != "true" ]; then mix dialyzer; fi

cache:
  directories:
    - priv/plts
