---

language: elixir
elixir:
  - 1.5.3
  - 1.6.6
  - 1.7.4
  - 1.8.2
otp_release:
  - 20.0
  - 20.3.8.22
  - 21.3.8
  - 22.1.3
matrix:
  exclude:
    - elixir: 1.5.3
      otp_release: 21.3.8
    - elixir: 1.5.3
      otp_release: 22.1.3
    - elixir: 1.6.6
      otp_release: 22.1.3
